"""
Django settings for blogsite project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-j1)41m67-2qn!u+%1t*urqdf*&kmwtmgd-bgmjdt-qm-(3$$4%',
)

def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", ["*"] if DEBUG else [])
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [])
USE_X_FORWARDED_HOST = env_bool("DJANGO_USE_X_FORWARDED_HOST", False)

if env_bool("DJANGO_USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", False)
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
APP_PUBLIC_BASE_URL = os.environ.get("APP_PUBLIC_BASE_URL", "").strip()
TERMINAL_WEB_TOKEN_MAX_AGE = int(os.environ.get("TERMINAL_WEB_TOKEN_MAX_AGE", "43200"))
TERMINAL_WEB_CAPTURE_LINES = int(os.environ.get("TERMINAL_WEB_CAPTURE_LINES", "200"))
TERMINAL_WEBSOCKET_POLL_SECONDS = float(
    os.environ.get("TERMINAL_WEBSOCKET_POLL_SECONDS", "1.0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("DJANGO_SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = os.environ.get(
    "DJANGO_SECURE_REFERRER_POLICY",
    "same-origin",
)


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blogsite.urls'
ASGI_APPLICATION = 'blogsite.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogsite.wsgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("DJANGO_DB_PATH", str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Asia/Shanghai")

USE_I18N = True

USE_TZ = env_bool("DJANGO_USE_TZ", True)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

OPENAI_API_URL = os.environ.get("OPENAI_API_URL", "http://125.94.105.18:52817/v1/responses")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.4")
OPENAI_REASONING_EFFORT = os.environ.get("OPENAI_REASONING_EFFORT", "xhigh")
OPENAI_TEXT_VERBOSITY = os.environ.get("OPENAI_TEXT_VERBOSITY", "medium")
OPENAI_REQUEST_TIMEOUT = int(os.environ.get("OPENAI_REQUEST_TIMEOUT", "60"))
CHAT_SYSTEM_PROMPT = os.environ.get(
    "CHAT_SYSTEM_PROMPT",
    "You are a concise and helpful assistant.",
)

FEISHU_BASE_URL = os.environ.get("FEISHU_BASE_URL", "https://open.feishu.cn")
FEISHU_APP_ID = os.environ.get("FEISHU_APP_ID", "")
FEISHU_APP_SECRET = os.environ.get("FEISHU_APP_SECRET", "")
FEISHU_VERIFICATION_TOKEN = os.environ.get("FEISHU_VERIFICATION_TOKEN", "")
FEISHU_BOT_NAME = os.environ.get("FEISHU_BOT_NAME", "linuxclaw")
FEISHU_EVENT_REPLY_TIMEOUT = int(os.environ.get("FEISHU_EVENT_REPLY_TIMEOUT", "15"))
FEISHU_REQUIRE_GROUP_MENTION = env_bool("FEISHU_REQUIRE_GROUP_MENTION", True)
FEISHU_CALENDAR_ID = os.environ.get("FEISHU_CALENDAR_ID", "")
FEISHU_CALENDAR_TIMEZONE = os.environ.get("FEISHU_CALENDAR_TIMEZONE", "Asia/Shanghai")
FEISHU_CALENDAR_AUTO_INVITE_SENDER = env_bool("FEISHU_CALENDAR_AUTO_INVITE_SENDER", True)
FEISHU_CALENDAR_LIST_PAGE_SIZE = int(os.environ.get("FEISHU_CALENDAR_LIST_PAGE_SIZE", "10"))
FEISHU_TERMINAL_ENABLED = env_bool("FEISHU_TERMINAL_ENABLED", True)
FEISHU_TERMINAL_ALLOWED_OPEN_IDS = env_list("FEISHU_TERMINAL_ALLOWED_OPEN_IDS", [])

REMOTE_SSH_HOST = os.environ.get("REMOTE_SSH_HOST", "")
REMOTE_SSH_PORT = int(os.environ.get("REMOTE_SSH_PORT", "22"))
REMOTE_SSH_USER = os.environ.get("REMOTE_SSH_USER", "")
REMOTE_SSH_PASSWORD = os.environ.get("REMOTE_SSH_PASSWORD", "")
REMOTE_SSH_IDENTITY_FILE = os.environ.get("REMOTE_SSH_IDENTITY_FILE", "")
REMOTE_PROJECT_ROOT = os.environ.get("REMOTE_PROJECT_ROOT", "")
REMOTE_READ_FILE_LIMIT = int(os.environ.get("REMOTE_READ_FILE_LIMIT", "12000"))
REMOTE_LIST_FILE_LIMIT = int(os.environ.get("REMOTE_LIST_FILE_LIMIT", "200"))
REMOTE_LIST_FILE_DEPTH = int(os.environ.get("REMOTE_LIST_FILE_DEPTH", "6"))
REMOTE_REQUIRE_CLEAN_WORKTREE = env_bool("REMOTE_REQUIRE_CLEAN_WORKTREE", True)
REMOTE_COMMAND_TIMEOUT = int(os.environ.get("REMOTE_COMMAND_TIMEOUT", "60"))
REMOTE_ALLOWED_TEST_PREFIXES = env_list(
    "REMOTE_ALLOWED_TEST_PREFIXES",
    [
        "python manage.py test",
        "pytest",
        "uv run pytest",
        "npm test",
        "pnpm test",
        "yarn test",
        "go test",
        "cargo test",
    ],
)
REMOTE_ALLOWED_INSPECTION_PREFIXES = env_list(
    "REMOTE_ALLOWED_INSPECTION_PREFIXES",
    [
        "df -h",
        "lsblk",
        "du -sh",
        "free -h",
        "uptime",
        "nproc",
        "docker ps",
        "docker images",
        "docker stats --no-stream",
        "ss -lntp",
        "ps aux --sort=-%mem",
        "ps aux --sort=-%cpu",
    ],
)
REMOTE_AGENT_SYSTEM_PROMPT = os.environ.get(
    "REMOTE_AGENT_SYSTEM_PROMPT",
    (
        "You are a careful remote coding planner. "
        "Return strict JSON only, minimize edits, and prefer safe, reversible changes."
    ),
)
REMOTE_TERMINAL_SESSION_PREFIX = os.environ.get("REMOTE_TERMINAL_SESSION_PREFIX", "linuxclaw")
REMOTE_TERMINAL_CAPTURE_LINES = int(os.environ.get("REMOTE_TERMINAL_CAPTURE_LINES", "80"))
REMOTE_TERMINAL_WAIT_SECONDS = float(os.environ.get("REMOTE_TERMINAL_WAIT_SECONDS", "0.6"))
REMOTE_TERMINAL_MAX_INPUT = int(os.environ.get("REMOTE_TERMINAL_MAX_INPUT", "2000"))
REMOTE_TERMINAL_SHELL_COMMAND = os.environ.get("REMOTE_TERMINAL_SHELL_COMMAND", "exec bash -li")
REMOTE_TERMINAL_CODEX_COMMAND = os.environ.get("REMOTE_TERMINAL_CODEX_COMMAND", "exec codex")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
